import type { Metadata } from "next";
import { Inter, Mona_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";
import { cn } from "@/lib/utils";
import { Footer } from "@/sections";
import Provider from "@/provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zort - AI-Powered Bet Tracking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={cn(
          ` ${inter.variable} ${monaSans.variable}`,
          "min-h-screen antialiased",
        )}
      >
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
